/*
 * Registro de íconos Lucide del proyecto (adaptación: reemplaza la descarga desde unpkg).
 * Solo los íconos listados entran al sitio, para que cargue rápido con mala conectividad.
 * ¿Necesitas otro? Búscalo en https://lucide.dev, agrégalo aquí (nombre en kebab-case)
 * y en el import. Los nombres que no estén registrados muestran un aviso en desarrollo.
 */
import {
  Accessibility,
  ArrowLeft,
  ArrowRight,
  Bell,
  CalendarDays,
  Car,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  Clock,
  Columns2,
  Construction,
  CreditCard,
  Download,
  Drama,
  Ellipsis,
  File,
  FileText,
  FileUp,
  FileUser,
  Files,
  Gift,
  GraduationCap,
  HandHeart,
  HeartPulse,
  Info,
  Landmark,
  Laptop,
  Link,
  LoaderCircle,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Paperclip,
  Phone,
  RotateCcw,
  Search,
  Send,
  ShieldCheck,
  Siren,
  Sparkles,
  Store,
  TrafficCone,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Upload,
  User,
  Users,
  Wallet,
  Wheat,
  X,
} from 'lucide-react';

export const ICONOS = {
  'accessibility': Accessibility,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'bell': Bell,
  'calendar-days': CalendarDays,
  'car': Car,
  'check': Check,
  'check-check': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle': Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'clock': Clock,
  'columns-2': Columns2,
  'construction': Construction,
  'credit-card': CreditCard,
  'download': Download,
  'drama': Drama,
  'ellipsis': Ellipsis,
  'file': File,
  'file-text': FileText,
  'file-up': FileUp,
  'file-user': FileUser,
  'files': Files,
  'gift': Gift,
  'graduation-cap': GraduationCap,
  'hand-heart': HandHeart,
  'heart-pulse': HeartPulse,
  'info': Info,
  'landmark': Landmark,
  'laptop': Laptop,
  'link': Link,
  'loader-circle': LoaderCircle,
  'mail': Mail,
  'map': Map,
  'map-pin': MapPin,
  'menu': Menu,
  'message-circle': MessageCircle,
  'mic': Mic,
  'minus': Minus,
  'paperclip': Paperclip,
  'phone': Phone,
  'rotate-ccw': RotateCcw,
  'search': Search,
  'send': Send,
  'shield-check': ShieldCheck,
  'siren': Siren,
  'sparkles': Sparkles,
  'store': Store,
  'traffic-cone': TrafficCone,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'trophy': Trophy,
  'upload': Upload,
  'user': User,
  'users': Users,
  'wallet': Wallet,
  'wheat': Wheat,
  'x': X,
};
