const A = '../../assets';
const TRAMITES = [
  { id: 'circulacion', cat: 'Tránsito', icon: 'car', title: 'Permiso de circulación', description: 'Renueva el permiso de tu vehículo sin ir a la Municipalidad.', requirements: ['Revisión técnica vigente', 'SOAP 2026', 'Permiso del año anterior'], cost: 'Según avalúo', duration: '10 minutos', modality: 'En línea', status: 'operativo' },
  { id: 'residencia', cat: 'Certificados', icon: 'house', title: 'Certificado de residencia', description: 'Acredita que vives en Hualañé para postular a beneficios o trámites.', requirements: ['Cédula de identidad', 'Boleta de luz o agua a tu nombre'], cost: 'Gratis', duration: '1 día hábil', modality: 'En línea', status: 'operativo' },
  { id: 'patente', cat: 'Comercio', icon: 'store', title: 'Patente comercial', description: 'Obtén o renueva la patente para tu negocio o emprendimiento.', requirements: ['Inicio de actividades en el SII', 'Contrato de arriendo o dominio', 'Resolución sanitaria si vendes alimentos'], cost: 'Desde 1 UTM', duration: '5 días hábiles', modality: 'En línea o presencial', status: 'operativo' },
  { id: 'licencia', cat: 'Tránsito', icon: 'id-card', title: 'Licencia de conducir', description: 'Reserva tu hora para obtener o renovar tu licencia.', requirements: ['Cédula de identidad', 'Certificado de estudios (primera vez)'], cost: 'Desde $ 22.000', duration: '1 mañana', modality: 'Presencial', status: 'intermitente' },
  { id: 'rsh', cat: 'Social', icon: 'users', title: 'Registro Social de Hogares', description: 'Ingresa o actualiza los datos de tu hogar para acceder a beneficios.', requirements: ['Cédula de todas las personas del hogar', 'Boleta de servicios'], cost: 'Gratis', duration: '15 días hábiles', modality: 'En línea o presencial', status: 'operativo' },
  { id: 'edificacion', cat: 'Vivienda y obras', icon: 'construction', title: 'Permiso de edificación', description: 'Pide autorización para construir o ampliar tu vivienda.', requirements: ['Plano firmado por arquitecto', 'Certificado de informaciones previas'], cost: 'Según m²', duration: '30 días', modality: 'Presencial', status: 'operativo' },
  { id: 'feria', cat: 'Comercio', icon: 'tent', title: 'Permiso para feria o evento', description: 'Autorización para ocupar un espacio público con tu puesto o actividad.', requirements: ['Cédula de identidad', 'Descripción de la actividad'], cost: 'Gratis para organizaciones', duration: '3 días hábiles', modality: 'En línea', status: 'suspendido' },
  { id: 'aseo', cat: 'Certificados', icon: 'trash-2', title: 'Retiro de voluminosos', description: 'Agenda el retiro de muebles, ramas o electrodomésticos en tu casa.', requirements: ['Dirección y sector'], cost: 'Gratis', duration: 'Próxima ruta', modality: 'En línea', status: 'operativo' },
];
Object.assign(window, { A, TRAMITES });
